// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq9qdvBnZxqjszs95v-vrYVdnVYbGtmHY',
    appId: '1:627405394553:web:797a1871213264b21dbaa8',
    messagingSenderId: '627405394553',
    projectId: 'ghalib-ai-db3ca',
    authDomain: 'ghalib-ai-db3ca.firebaseapp.com',
    storageBucket: 'ghalib-ai-db3ca.firebasestorage.app',
    measurementId: 'G-ZWZCW5ZTJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHujk-rYIYUfpqmqo2tNnBuAJvkKWHIvI',
    appId: '1:627405394553:android:fc82e2a1d3b5820e1dbaa8',
    messagingSenderId: '627405394553',
    projectId: 'ghalib-ai-db3ca',
    storageBucket: 'ghalib-ai-db3ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR7kb9uaep1c1dVFCxZvuIPU62W-g99ho',
    appId: '1:627405394553:ios:364ff91275632e3a1dbaa8',
    messagingSenderId: '627405394553',
    projectId: 'ghalib-ai-db3ca',
    storageBucket: 'ghalib-ai-db3ca.firebasestorage.app',
    iosBundleId: 'com.example.ghalib',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR7kb9uaep1c1dVFCxZvuIPU62W-g99ho',
    appId: '1:627405394553:ios:364ff91275632e3a1dbaa8',
    messagingSenderId: '627405394553',
    projectId: 'ghalib-ai-db3ca',
    storageBucket: 'ghalib-ai-db3ca.firebasestorage.app',
    iosBundleId: 'com.example.ghalib',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq9qdvBnZxqjszs95v-vrYVdnVYbGtmHY',
    appId: '1:627405394553:web:775f46f2ae3fe1d71dbaa8',
    messagingSenderId: '627405394553',
    projectId: 'ghalib-ai-db3ca',
    authDomain: 'ghalib-ai-db3ca.firebaseapp.com',
    storageBucket: 'ghalib-ai-db3ca.firebasestorage.app',
    measurementId: 'G-KJVRHYT66T',
  );
}
